/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import tiendavirtual.*;
/**
**
** @author Luis Alonso Corella Chaves - 05/10/2017
**/
public class VentanaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form VentanaPRincipal
     */
    private Logica log;
    public VentanaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        log = new Logica();
    }
    public VentanaPrincipal(Logica log) {
        initComponents();
        setLocationRelativeTo(null);
        this.log = log;
        lblUsuarioLogeado.setText(this.log.logueado().getNombre());
        vistaDeGenero();
    }
    public void irAVentanaLogin(){
        VentanaLogin login =  new VentanaLogin(log);
        login.setVisible(true);
        dispose();
    }
    public void irAVentanaDaTosUsuario(){
        VentanaDatosUsuario editar = new VentanaDatosUsuario(log);
        editar.setVisible(true);
        dispose();
    }
    public void irARegistroProducto(){
        VentanaRegistroProducto producto = new VentanaRegistroProducto(log);
        producto.setVisible(true);
        dispose();
    }
    public void vistaDeGenero(){
        if(log.logueado() instanceof Usuario){
            if(((Usuario) log.logueado()).getSexo() == 0){
                btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/Imagenes/editarUsuarioMujer.png")));
            }else if(((Usuario) log.logueado()).getSexo() == 1){
                btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/Imagenes/editarUsuarioHombre.png")));
            }
        }else if(log.logueado() instanceof Administrador){
            btnCarritoEditar.setIcon(new javax.swing.ImageIcon(getClass().
                        getResource("/Imagenes/editarProducto.png")));
            btnCarritoEditar.setText("Editar Prod.");
            btnVerProductos.setText("Agregar Prod.");
        }
    }
    public void irAVentanaTablaProductos(){
        VentanaListaProducto tabla = new VentanaListaProducto(log);
        tabla.setVisible(true);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditarPerfil = new javax.swing.JButton();
        lblUsuarioLogeado = new javax.swing.JLabel();
        btnVerProductos = new javax.swing.JButton();
        btnCarritoEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnEditarPerfil.setBackground(new java.awt.Color(0, 204, 0));
        btnEditarPerfil.setForeground(new java.awt.Color(233, 110, 35));
        btnEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editarUsuarioHombre.png"))); // NOI18N
        btnEditarPerfil.setText("Editar Perfil");
        btnEditarPerfil.setToolTipText("");
        btnEditarPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarPerfil.setMaximumSize(new java.awt.Dimension(99, 75));
        btnEditarPerfil.setMinimumSize(new java.awt.Dimension(99, 75));
        btnEditarPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPerfilActionPerformed(evt);
            }
        });

        lblUsuarioLogeado.setForeground(new java.awt.Color(153, 255, 153));
        lblUsuarioLogeado.setText("---");

        btnVerProductos.setBackground(new java.awt.Color(0, 204, 0));
        btnVerProductos.setForeground(new java.awt.Color(233, 110, 35));
        btnVerProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verProductos.png"))); // NOI18N
        btnVerProductos.setText("Ver Productos");
        btnVerProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProductosActionPerformed(evt);
            }
        });

        btnCarritoEditar.setBackground(new java.awt.Color(0, 204, 0));
        btnCarritoEditar.setForeground(new java.awt.Color(233, 110, 35));
        btnCarritoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carritoDeCompras.png"))); // NOI18N
        btnCarritoEditar.setText("Carrito");
        btnCarritoEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarritoEditar.setMaximumSize(new java.awt.Dimension(99, 75));
        btnCarritoEditar.setMinimumSize(new java.awt.Dimension(99, 75));
        btnCarritoEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarritoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoEditarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Bienvenidos a la Tienda Virtual.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnVerProductos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnCarritoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUsuarioLogeado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(lblUsuarioLogeado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEditarPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(75, 75, 75)
                .addComponent(btnCarritoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        irAVentanaLogin();
    }//GEN-LAST:event_formWindowClosing
    private void btnEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPerfilActionPerformed
        log.setTipoDeVistaDatosUsu(false);
        irAVentanaDaTosUsuario();
    }//GEN-LAST:event_btnEditarPerfilActionPerformed
    private void btnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosActionPerformed
        log.setTipoDeVistaProductos(true);
        irARegistroProducto();
    }//GEN-LAST:event_btnVerProductosActionPerformed
    private void btnCarritoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoEditarActionPerformed
        if(log.vistaDatosUsuario() == true){
            
        }else if(log.vistaDatosUsuario() == false){
            log.setTipoDeVistaProductos(false);
            irAVentanaTablaProductos();
        }
    }//GEN-LAST:event_btnCarritoEditarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarritoEditar;
    private javax.swing.JButton btnEditarPerfil;
    private javax.swing.JButton btnVerProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuarioLogeado;
    // End of variables declaration//GEN-END:variables
}